name: Deploy to Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore mtime
      uses: chetan/git-restore-mtime-action@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies & Build Vite
      run: |
        npm install
        npm run build

    - name: Install LFTP
      run: sudo apt-get install -y lftp

    - name: Sync files via LFTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "set ftp:ssl-allow no; set net:max-retries 3; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror --reverse --verbose --only-newer --parallel=2 --exclude-glob .git/ --exclude-glob .github/ --exclude-glob node_modules/ --exclude-glob vendor/ --exclude-glob .env . /; quit;"
